### PR TITLE
finalProductForm

### PR DESCRIPTION
**Pull request by dhobson21**
-No more image upload
-unauthenticated users redirected to login when clicking form link
-check on if product category drop down has selected option
-check on quantity as whole number
-price added to db in correct format and displayed in correct format

### CODE REVIEW

**Comment by TylerCarpenter92** [comment]
👍 all is well

**Comment by DannyBarker** [comment]
👍 nice job. Just delete the image tag from product card component and product.js in home directory

**Comment by TylerCarpenter92** [comment]
👍

**Comment by DannyBarker** [comment]
👍

**Pull request merged**
